spring:
  application:
    name: registration-service
  r2dbc:
    url: r2dbc:h2:file:///./.reg_db
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: true
    default-schema: public
    url: jdbc:h2:file:./.reg_db
h2-server:
  port: 8081
users:
  count: 2
logging:
  level:
    root: INFO
