spring:
  application:
    name: registration-service
  r2dbc:
    url: r2dbc:h2:file:///./reg_db
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: true
    default-schema: public
    datasource:
      url: r2dbc:h2:file:///./reg_db
      username: sa
      password:

users:
  count: 2
